### ISSUE TITLE
How do I increase the root filesystem size?

### ISSUE THREAD

**Issue by bgurney-rh** [containers/crun-qemu#11]
Hi,

I was able to try this, and it seemed to work nicely, resulting in a qemu virtual machine:
```
$ ls f39-image/ | cat
etc
Fedora-Cloud-Base-39-1.5.x86_64.qcow2

$ podman run --runtime "$PWD"/target/debug/crun-qemu -it --cpus=3 --memory=2560m --rm --rootfs f39-image ""
...
Fedora Linux 39 (Cloud Edition)
Kernel 6.5.6-300.fc39.x86_64 on an x86_64 (ttyS0)
...
[fedora@f81862e6b4d0 ~]$ df /
Filesystem     1K-blocks   Used Available Use% Mounted on
/dev/vda5        4109312 463096   3171784  13% /
```

It created what looks like a 4 GiB btrfs filesystem.  Is there a way that I could increase the size?  (I started this qemu process on a VM with about 13 GiB of free space, so it would be interesting to know if I should be aware of free space requirements on the host.)

**Comment by albertofaria** [comment]
Root filesystem size is fully determined by the VM image you're using, which crun-qemu simply passes through to libvirt/qemu unmodified. You can use tools like [virt-resize](https://libguestfs.org/virt-resize.1.html) to resize disks for an existing VM image.
