### ISSUE TITLE
DOC Installation - Need to install libselinux-devel

### ISSUE THREAD

**Issue by johwes** [containers/crun-qemu#3]
Hi,

As part of the documentation to build crun-qemu, there is a list of packages to install.

I also needed to install libselinux-devel otherwise i got the following error during build,

  = note: /usr/bin/ld: cannot find -lselinux: No such file or directory
          collect2: error: ld returned 1 exit status
          

error: could not compile `crun-qemu` (bin "crun-qemu") due to previous error

After,
sudo dnf install libselinux-devel

It worked,
 cargo build
   Compiling crun-qemu v0.0.0 (/src/crun-qemu)
    Finished dev [unoptimized + debuginfo] target(s) in 0.78s

**Comment by albertofaria** [comment]
Thanks, I fixed the docs. Let me know if you have any other issue.
