### ISSUE TITLE
Unable to run the fedora:39 containerdisk

### ISSUE THREAD

**Issue by johwes** [containers/crun-qemu#6]
I'm trying to run the doc example,

My machine is Fedora 39 silverblue

$ uname -a
Linux fedora 6.6.9-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jan  1 20:05:54 UTC 2024 x86_64 GNU/Linux

$ podman run --log-level debug --runtime "$PWD"/target/debug/crun-qemu -it --rm quay.io/containerdisks/fedora:39 ""

INFO[0000] podman filtering at log level debug          
DEBU[0000] Called run.PersistentPreRunE(podman run --log-level debug --runtime /var/home/jwesterl/bootc/crun-qemu/target/debug/crun-qemu -it --rm quay.io/containerdisks/fedora:39 ) 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
INFO[0000] Using boltdb as database backend             
DEBU[0000] Initializing boltdb state at /home/jwesterl/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Overriding graph root "/var/home/jwesterl/.local/share/containers/storage" with "/home/jwesterl/.local/share/containers/storage" from database 
DEBU[0000] Overriding volume path "/home/jwesterl/.local/share/containers/storage/libpod" with "/home/jwesterl/.local/share/containers/storage/volumes" from database 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/jwesterl/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/25059/containers    
DEBU[0000] Using static dir /home/jwesterl/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/25059/libpod/tmp     
DEBU[0000] Using volume path /home/jwesterl/.local/share/containers/storage/volumes 
DEBU[0000] Using transient store: false                 
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that metacopy is not being used 
DEBU[0000] Cached value indicated that native-diff is usable 
DEBU[0000] backingFs=btrfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Initializing event backend journald          
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument 
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument 
DEBU[0000] Configured OCI runtime ocijail initialization failed: no valid executable found for OCI runtime ocijail: invalid argument 
DEBU[0000] Configured OCI runtime crun-wasm initialization failed: no valid executable found for OCI runtime crun-wasm: invalid argument 
DEBU[0000] Configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument 
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] Configured OCI runtime youki initialization failed: no valid executable found for OCI runtime youki: invalid argument 
DEBU[0000] Using OCI runtime "/var/home/jwesterl/bootc/crun-qemu/target/debug/crun-qemu" 
INFO[0000] Setting parallel job count to 25             
DEBU[0000] Successfully loaded network podman-default-kube-network: &{podman-default-kube-network 9056d64605b66705d6063f6c54c7d4b02ea98009d3636bbf8df5ab59cd7e7f6c bridge podman1 2023-05-02 10:08:24.087279997 +0200 CEST [{{{10.89.0.0 ffffff00}} 10.89.0.1 <nil>}] [] false false true [] map[] map[] map[driver:host-local]} 
DEBU[0000] Successfully loaded network podman: &{podman 2f259bab93aaaaa2542ba43ef33eb990d0999ee1b9924b557b7be53c0b7a1bb9 bridge podman0 2023-05-02 14:46:42.665278835 +0200 CEST [{{{10.88.0.0 ffff0000}} 10.88.0.1 <nil>}] [] false false false [] map[] map[] map[driver:host-local]} 
DEBU[0000] Successfully loaded 2 networks               
DEBU[0000] Pulling image quay.io/containerdisks/fedora:39 (policy: missing) 
DEBU[0000] Looking up image "quay.io/containerdisks/fedora:39" in local containers storage 
DEBU[0000] Normalized platform linux/amd64 to {amd64 linux  [] } 
DEBU[0000] Trying "quay.io/containerdisks/fedora:39" ... 
DEBU[0000] parsed reference into "[overlay@/home/jwesterl/.local/share/containers/storage+/run/user/25059/containers]@a85e682c84b7c54b29f57def07571d83282da6d0bae7ff60a7ba91bfc0bc6455" 
DEBU[0000] Found image "quay.io/containerdisks/fedora:39" as "quay.io/containerdisks/fedora:39" in local containers storage 
DEBU[0000] Found image "quay.io/containerdisks/fedora:39" as "quay.io/containerdisks/fedora:39" in local containers storage ([overlay@/home/jwesterl/.local/share/containers/storage+/run/user/25059/containers]@a85e682c84b7c54b29f57def07571d83282da6d0bae7ff60a7ba91bfc0bc6455) 
DEBU[0000] exporting opaque data as blob "sha256:a85e682c84b7c54b29f57def07571d83282da6d0bae7ff60a7ba91bfc0bc6455" 
DEBU[0000] Looking up image "quay.io/containerdisks/fedora:39" in local containers storage 
DEBU[0000] Normalized platform linux/amd64 to {amd64 linux  [] } 
DEBU[0000] Trying "quay.io/containerdisks/fedora:39" ... 
DEBU[0000] parsed reference into "[overlay@/home/jwesterl/.local/share/containers/storage+/run/user/25059/containers]@a85e682c84b7c54b29f57def07571d83282da6d0bae7ff60a7ba91bfc0bc6455" 
DEBU[0000] Found image "quay.io/containerdisks/fedora:39" as "quay.io/containerdisks/fedora:39" in local containers storage 
DEBU[0000] Found image "quay.io/containerdisks/fedora:39" as "quay.io/containerdisks/fedora:39" in local containers storage ([overlay@/home/jwesterl/.local/share/containers/storage+/run/user/25059/containers]@a85e682c84b7c54b29f57def07571d83282da6d0bae7ff60a7ba91bfc0bc6455) 
DEBU[0000] exporting opaque data as blob "sha256:a85e682c84b7c54b29f57def07571d83282da6d0bae7ff60a7ba91bfc0bc6455" 
DEBU[0000] Looking up image "quay.io/containerdisks/fedora:39" in local containers storage 
DEBU[0000] Normalized platform linux/amd64 to {amd64 linux  [] } 
DEBU[0000] Trying "quay.io/containerdisks/fedora:39" ... 
DEBU[0000] parsed reference into "[overlay@/home/jwesterl/.local/share/containers/storage+/run/user/25059/containers]@a85e682c84b7c54b29f57def07571d83282da6d0bae7ff60a7ba91bfc0bc6455" 
DEBU[0000] Found image "quay.io/containerdisks/fedora:39" as "quay.io/containerdisks/fedora:39" in local containers storage 
DEBU[0000] Found image "quay.io/containerdisks/fedora:39" as "quay.io/containerdisks/fedora:39" in local containers storage ([overlay@/home/jwesterl/.local/share/containers/storage+/run/user/25059/containers]@a85e682c84b7c54b29f57def07571d83282da6d0bae7ff60a7ba91bfc0bc6455) 
DEBU[0000] exporting opaque data as blob "sha256:a85e682c84b7c54b29f57def07571d83282da6d0bae7ff60a7ba91bfc0bc6455" 
DEBU[0000] Inspecting image a85e682c84b7c54b29f57def07571d83282da6d0bae7ff60a7ba91bfc0bc6455 
DEBU[0000] exporting opaque data as blob "sha256:a85e682c84b7c54b29f57def07571d83282da6d0bae7ff60a7ba91bfc0bc6455" 
DEBU[0000] exporting opaque data as blob "sha256:a85e682c84b7c54b29f57def07571d83282da6d0bae7ff60a7ba91bfc0bc6455" 
DEBU[0000] Inspecting image a85e682c84b7c54b29f57def07571d83282da6d0bae7ff60a7ba91bfc0bc6455 
DEBU[0000] Inspecting image a85e682c84b7c54b29f57def07571d83282da6d0bae7ff60a7ba91bfc0bc6455 
DEBU[0000] Inspecting image a85e682c84b7c54b29f57def07571d83282da6d0bae7ff60a7ba91bfc0bc6455 
DEBU[0000] using systemd mode: false                    
DEBU[0000] No hostname set; container's hostname will default to runtime default 
DEBU[0000] Loading seccomp profile from "/usr/share/containers/seccomp.json" 
DEBU[0000] Allocated lock 3 for container 0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956 
DEBU[0000] parsed reference into "[overlay@/home/jwesterl/.local/share/containers/storage+/run/user/25059/containers]@a85e682c84b7c54b29f57def07571d83282da6d0bae7ff60a7ba91bfc0bc6455" 
DEBU[0000] exporting opaque data as blob "sha256:a85e682c84b7c54b29f57def07571d83282da6d0bae7ff60a7ba91bfc0bc6455" 
DEBU[0000] Cached value indicated that idmapped mounts for overlay are not supported 
DEBU[0000] Check for idmapped mounts support            
DEBU[0000] Created container "0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956" 
DEBU[0000] Container "0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956" has work directory "/home/jwesterl/.local/share/containers/storage/overlay-containers/0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956/userdata" 
DEBU[0000] Container "0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956" has run directory "/run/user/25059/containers/overlay-containers/0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956/userdata" 
DEBU[0000] Handling terminal attach                     
INFO[0000] Received shutdown.Stop(), terminating!        PID=30304
DEBU[0000] Enabling signal proxying                     
DEBU[0000] Cached value indicated that volatile is being used 
DEBU[0000] overlay: mount_data=lowerdir=/home/jwesterl/.local/share/containers/storage/overlay/l/XNMIBJLZDS5ELNIWTLKWFMVKLV,upperdir=/home/jwesterl/.local/share/containers/storage/overlay/06fe0013493c5fd1ee689cc2fd4543403a69ef6cac7fe8537543b53f62be02f9/diff,workdir=/home/jwesterl/.local/share/containers/storage/overlay/06fe0013493c5fd1ee689cc2fd4543403a69ef6cac7fe8537543b53f62be02f9/work,userxattr,volatile,context="system_u:object_r:container_file_t:s0:c215,c640" 
DEBU[0000] Made network namespace at /run/user/25059/netns/netns-80a429fb-7e70-4ff1-10d2-bff7059ee352 for container 0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956 
DEBU[0000] Mounted container "0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956" at "/home/jwesterl/.local/share/containers/storage/overlay/06fe0013493c5fd1ee689cc2fd4543403a69ef6cac7fe8537543b53f62be02f9/merged" 
DEBU[0000] Created root filesystem for container 0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956 at /var/home/jwesterl/.local/share/containers/storage/overlay/06fe0013493c5fd1ee689cc2fd4543403a69ef6cac7fe8537543b53f62be02f9/merged 
DEBU[0000] slirp4netns command: /usr/bin/slirp4netns --disable-host-loopback --mtu=65520 --enable-sandbox --enable-seccomp --enable-ipv6 -c -r 3 -e 4 --netns-type=path /run/user/25059/netns/netns-80a429fb-7e70-4ff1-10d2-bff7059ee352 tap0 
DEBU[0000] /etc/system-fips does not exist on host, not mounting FIPS mode subscription 
DEBU[0000] Setting Cgroups for container 0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956 to user.slice:libpod:0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956 
DEBU[0000] reading hooks from /usr/share/containers/oci/hooks.d 
DEBU[0000] Workdir "/" resolved to host path "/var/home/jwesterl/.local/share/containers/storage/overlay/06fe0013493c5fd1ee689cc2fd4543403a69ef6cac7fe8537543b53f62be02f9/merged" 
DEBU[0000] Created OCI spec for container 0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956 at /home/jwesterl/.local/share/containers/storage/overlay-containers/0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956/userdata/config.json 
DEBU[0000] /usr/bin/conmon messages will be logged to syslog 
DEBU[0000] running conmon: /usr/bin/conmon               args="[--api-version 1 -c 0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956 -u 0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956 -r /var/home/jwesterl/bootc/crun-qemu/target/debug/crun-qemu -b /home/jwesterl/.local/share/containers/storage/overlay-containers/0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956/userdata -p /run/user/25059/containers/overlay-containers/0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956/userdata/pidfile -n vigilant_maxwell --exit-dir /run/user/25059/libpod/tmp/exits --full-attach -s -l journald --log-level debug --syslog -t --conmon-pidfile /run/user/25059/containers/overlay-containers/0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /home/jwesterl/.local/share/containers/storage --exit-command-arg --runroot --exit-command-arg /run/user/25059/containers --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /run/user/25059/libpod/tmp --exit-command-arg --network-config-dir --exit-command-arg  --exit-command-arg --network-backend --exit-command-arg netavark --exit-command-arg --volumepath --exit-command-arg /home/jwesterl/.local/share/containers/storage/volumes --exit-command-arg --db-backend --exit-command-arg boltdb --exit-command-arg --transient-store=false --exit-command-arg --runtime --exit-command-arg /var/home/jwesterl/bootc/crun-qemu/target/debug/crun-qemu --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --events-backend --exit-command-arg journald --exit-command-arg --syslog --exit-command-arg container --exit-command-arg cleanup --exit-command-arg --rm --exit-command-arg 0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956]"
INFO[0000] Running conmon under slice user.slice and unitName libpod-conmon-0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956.scope 
DEBU[0000] Received: -1                                 
DEBU[0000] Cleaning up container 0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956 
DEBU[0000] Tearing down network namespace at /run/user/25059/netns/netns-80a429fb-7e70-4ff1-10d2-bff7059ee352 for container 0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956 
DEBU[0000] Unmounted container "0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956" 
DEBU[0000] Removing container 0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956 
DEBU[0000] Cleaning up container 0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956 
DEBU[0000] Network is already cleaned up, skipping...   
DEBU[0000] Container 0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956 storage is already unmounted, skipping... 
DEBU[0000] Removing all exec sessions for container 0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956 
DEBU[0000] Container 0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956 storage is already unmounted, skipping... 
DEBU[0000] Failed to delete container "0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956": 1 error occurred:
	* unlinkat /home/jwesterl/.local/share/containers/storage/overlay-containers/0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956/userdata/crun-qemu-root/crun-qemu: directory not empty
 
DEBU[0000] unable to remove container 0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956 after failing to start and attach to it: cleaning up storage: removing container 0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956 root filesystem: 1 error occurred:
	* unlinkat /home/jwesterl/.local/share/containers/storage/overlay-containers/0e957eea6bec3aaaac2fa5cf9467bfda68a9327d061805bd64ca19de4d30f956/userdata/crun-qemu-root/crun-qemu: directory not empty
 
DEBU[0000] ExitCode msg: "/var/home/jwesterl/bootc/crun-qemu/target/debug/crun-qemu: failed to load cloud-init config: no such file or directory (os error 2): oci runtime attempted to invoke a command that was not found" 
Error: /var/home/jwesterl/bootc/crun-qemu/target/debug/crun-qemu: failed to load cloud-init config: No such file or directory (os error 2): OCI runtime attempted to invoke a command that was not found
DEBU[0000] Shutting down engines

**Comment by johwes** [comment]
Hmm, It might be my bad,
Since i have silverblue, I built the crun-qemu binary in a toolbox.
But in the docs it says runtime dependencies, hence it might be that I lack some of the dependencies "outside" the toolbox container.

**Comment by albertofaria** [comment]
The "OCI runtime attempted to invoke a command that was not found" message that podman adds is sometimes a red herring.

Is genisoimage in your PATH? Are you able to run regular containers without crun-qemu inside the toolbox?

**Comment by johwes** [comment]
I installed genisoimage and this problem went away!
